### PR TITLE
Fix race in throttle node

### LINKED ISSUE #55: Segmentation fault [ros2run]
## Description
Segmentation fault occurring when stopping the publisher and restarting while keeping the ros2 run topic throttle message active. 

In two separate terminals, publish two messages 
$ ros2 topic pub -r 10 /greetings std_msgs/msg/String "{data: 'Hello from terminal'}"
$ ros2 topic pub -r 10 /welcome std_msgs/msg/String "{data: 'Hello from terminal'}"

In two new terminals, run the commands, 
$ ros2 run topic_tools throttle messages /greetings 1
$ ros2 run topic_tools throttle messages /welcome 1

on doing a ros2 topic list, the following topics are visible:
/greetings
/greetings_throttle
/parameter_events
/rosout
/welcome
/welcome_throttle

Press control + c in terminal two (or in one) where the $ ros2 topic pub -r 10 /welcome std_msgs/msg/String "{data: 'Hello from terminal'}" was entered. 

and rerun the command again. 

### Expected Behavior
** clear and concise description of what you _expected_ to happen **

### Actual Behavior
** clear and concise description of what _actually_ happened. include copied logs whenever possible **
In the terminal where the following command was entered, $ ros2 run topic_tools throttle messages /welcome 
the following occurred. 
[ros2run]: Segmentation fault
 

## System (please complete the following information)
 - OS: Ubuntu 22.04
 - ROS 2 Distro: Humble

Is there any chance to keep the throttle active and connect again without segmentation fault when the topic starts to publish again?

Additional info
Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.5', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 89, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/command/topic.py", line 41, in main
    return extension.main(args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/verb/hz.py", line 89, in main
    return main(args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/verb/hz.py", line 104, in main
    _rostopic_hz(node.node, topic, window_size=args.window_size, filter_expr=filter_expr,
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/verb/hz.py", line 274, in _rostopic_hz
    rt.print_hz(topic)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/verb/hz.py", line 244, in print_hz
    print('average rate: %.3f\n\tmin: %.3fs max: %.3fs std dev: %.5fs window: %s'
BrokenPipeError: [Errno 32] Broken pipe

Thanks

### PR DESCRIPTION
**Pull request by christophebedard**
Fixes #55

See https://github.com/ros-tooling/topic_tools/issues/55#issuecomment-1465007875

This is the same fix as in #49

### CODE REVIEW

**Comment by christophebedard** [comment]
We should probably apply this fix to the other nodes as well.

File: topic_tools/src/throttle_node.cpp [hunk 1]
```diff
@@ -55,6 +55,11 @@ ThrottleNode::ThrottleNode(const rclcpp::NodeOptions & options)
 
 void ThrottleNode::process_message(std::shared_ptr<rclcpp::SerializedMessage> msg)
 {
+  std::scoped_lock lock(pub_mutex_);
```
Comment (christophebedard) [inline topic_tools/src/throttle_node.cpp:58]: This lock was added in #49, but in practice it's not really needed since the `topic_tools` nodes all use the single-threaded executor by default

**Review by emersonknapp — APPROVED** [review]
